#!/usr/bin/env python3
"""Encode Drift Los Angeles's mastered stereo music loop for the Dreamcast mixer."""

from __future__ import annotations

import argparse
import aifc
import audioop
import hashlib
import subprocess
import tempfile
from pathlib import Path


MUSIC_RATE = 22_050
MUSIC_CHANNELS = 2
MUSIC_WIDTH = 2


def decode_with_afconvert(source: Path) -> tuple[int, bytes]:
    """Decode any Core Audio input to fixed-rate, big-endian AIFF PCM."""
    with tempfile.TemporaryDirectory(prefix="drift-los-angeles-music-") as directory:
        decoded = Path(directory) / "music.aiff"
        subprocess.run(
            [
                "afconvert",
                "-f",
                "AIFF",
                "-d",
                f"BEI16@{MUSIC_RATE}",
                "-c",
                str(MUSIC_CHANNELS),
                str(source),
                str(decoded),
            ],
            check=True,
        )
        with aifc.open(str(decoded), "rb") as stream:
            if stream.getnchannels() != MUSIC_CHANNELS:
                raise ValueError("decoded music is not stereo")
            if stream.getframerate() != MUSIC_RATE:
                raise ValueError("decoded music has the wrong sample rate")
            if stream.getsampwidth() != MUSIC_WIDTH:
                raise ValueError("decoded music is not 16-bit PCM")
            if stream.getcomptype() != b"NONE":
                raise ValueError("decoded music is still compressed")
            frames = stream.getnframes()
            big_endian_pcm = stream.readframes(frames)

    # audioop consumes native/little-endian 16-bit samples on the host.
    little_endian_pcm = audioop.byteswap(big_endian_pcm, MUSIC_WIDTH)
    return frames, little_endian_pcm


def build(source: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    frames, pcm = decode_with_afconvert(source)
    if frames < MUSIC_RATE * 8:
        raise ValueError("music source is too short to function as a soundtrack")

    # G.711 mu-law keeps far more low-level musical detail than linear 8-bit
    # PCM while requiring only one byte per stereo sample. Runtime decoding is
    # two table lookups per frame, leaving the SH-4 free for physics/rendering.
    average = audioop.avg(pcm, MUSIC_WIDTH)
    pcm = audioop.bias(pcm, MUSIC_WIDTH, -average)
    encoded = audioop.lin2ulaw(pcm, MUSIC_WIDTH)
    if len(encoded) != frames * MUSIC_CHANNELS:
        raise RuntimeError("unexpected mu-law payload length")

    header = f"""/* Generated by tools/build_music_asset.py. Do not edit. */
#ifndef DRIFT_LA_MUSIC_ASSET_H
#define DRIFT_LA_MUSIC_ASSET_H

#include <stdint.h>

#define DLA_MUSIC_RATE {MUSIC_RATE}u
#define DLA_MUSIC_CHANNELS {MUSIC_CHANNELS}u
#define DLA_MUSIC_FRAMES {frames}u
#define DLA_MUSIC_BYTES {len(encoded)}u
extern const uint8_t dla_music_mulaw[];

#endif
"""
    assembly = """/* Generated by tools/build_music_asset.py. Do not edit. */
    .section .rodata
    .align 5
    .global _dla_music_mulaw
    .type _dla_music_mulaw, @object
_dla_music_mulaw:
    .incbin \"assets/generated/music_asset.mulaw\"
    .size _dla_music_mulaw, . - _dla_music_mulaw
"""

    (output_dir / "music_asset.h").write_text(header, encoding="utf-8")
    (output_dir / "music_asset.S").write_text(assembly, encoding="utf-8")
    (output_dir / "music_asset.mulaw").write_bytes(encoded)

    decoded = audioop.ulaw2lin(encoded, MUSIC_WIDTH)
    rms = audioop.rms(decoded, MUSIC_WIDTH) / 32768.0
    peak = audioop.max(decoded, MUSIC_WIDTH) / 32768.0
    digest = hashlib.sha256(encoded).hexdigest()
    print(
        f"music: {frames} frames, {frames / MUSIC_RATE:.3f}s, stereo "
        f"{MUSIC_RATE} Hz mu-law, RMS {rms:.3f}, peak {peak:.3f}"
    )
    print(f"music: {len(encoded) / (1024 * 1024):.2f} MiB, SHA-256 {digest}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    build(args.source.resolve(), args.output_dir.resolve())


if __name__ == "__main__":
    main()
