"""Shared mesh-rig authoring and C export for Drift Los Angeles generators.

A rig is a list of parts. Each part stores vertices relative to its pivot,
its parent part, and a slot id the game uses to pick a tint and atlas column.
Both the pedestrian and vehicle generators build parts with these helpers and
emit the same C types, guarded so either header can be included first.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Part:
    name: str
    parent: int
    pivot: tuple[float, float, float]
    region: str
    slot: str
    vertices: list[tuple[float, ...]] = field(default_factory=list)   # x y z u v nx ny nz
    faces: list[tuple[int, int, int]] = field(default_factory=list)

    def add_vertex(self, position, uv, normal) -> int:
        self.vertices.append((*position, *uv, *normal))
        return len(self.vertices) - 1


def normalize(v: tuple[float, float, float]) -> tuple[float, float, float]:
    length = math.sqrt(v[0] ** 2 + v[1] ** 2 + v[2] ** 2) or 1.0
    return (v[0] / length, v[1] / length, v[2] / length)


def dedupe_vertices(part: Part) -> None:
    """Share identical vertices between faces so the runtime transforms each once."""
    remap: dict[tuple[float, ...], int] = {}
    vertices: list[tuple[float, ...]] = []
    index_map = []
    for v in part.vertices:
        key = tuple(round(value, 4) for value in v)
        if key not in remap:
            remap[key] = len(vertices)
            vertices.append(v)
        index_map.append(remap[key])
    part.vertices = vertices
    part.faces = [(index_map[a], index_map[b], index_map[c]) for a, b, c in part.faces]


def fix_winding(part: Part) -> None:
    """Orient every face so its geometric normal agrees with its vertex normals,
    then share duplicate vertices."""
    dedupe_vertices(part)
    fixed = []
    for a, b, c in part.faces:
        va, vb, vc = part.vertices[a], part.vertices[b], part.vertices[c]
        ab = (vb[0] - va[0], vb[1] - va[1], vb[2] - va[2])
        ac = (vc[0] - va[0], vc[1] - va[1], vc[2] - va[2])
        n = (ab[1] * ac[2] - ab[2] * ac[1], ab[2] * ac[0] - ab[0] * ac[2], ab[0] * ac[1] - ab[1] * ac[0])
        if n[0] ** 2 + n[1] ** 2 + n[2] ** 2 < 1e-12:
            continue
        avg = (va[5] + vb[5] + vc[5], va[6] + vb[6] + vc[6], va[7] + vb[7] + vc[7])
        if n[0] * avg[0] + n[1] * avg[1] + n[2] * avg[2] < 0.0:
            fixed.append((a, c, b))
        else:
            fixed.append((a, b, c))
    part.faces = fixed


RIG_TYPES = """#ifndef DLA_RIG_TYPES_DEFINED
#define DLA_RIG_TYPES_DEFINED
/* Positions are relative to the owning part's pivot; UVs address the
   part's default atlas region. */
typedef struct { float x, y, z; float u, v; float nx, ny, nz; } dla_rig_vertex_t;
typedef struct { uint16_t a, b, c; } dla_rig_face_t;
typedef struct {
    int8_t parent;
    uint8_t slot;
    float pivot_x, pivot_y, pivot_z;
    uint16_t first_vertex, vertex_count, first_face, face_count;
} dla_rig_part_t;
typedef struct {
    const dla_rig_vertex_t *vertices;
    const dla_rig_face_t *faces;
    const dla_rig_part_t *parts;
    uint16_t vertex_count, face_count, part_count;
} dla_rig_mesh_t;
#define DLA_RIG_MAX_PARTS 24
#endif
"""


def write_rig_header(path: Path, guard: str, generator: str,
                     part_enum_prefix: str, part_names: list[str],
                     slot_enum_prefix: str, slot_names: list[str],
                     meshes: dict[str, list[Part]], extra_defines: list[str],
                     table_name: str, table_shape: str, table_rows: list[list[str]]) -> None:
    """Write every mesh in ``meshes`` (name -> parts) plus a lookup table.

    ``table_rows`` lists mesh names in the order the C table should reference
    them; ``table_shape`` is the C array suffix, e.g. ``[5][3]``.
    """
    lines = [
        f"/* Generated by {generator}. Do not edit by hand. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        RIG_TYPES,
        "enum { " + ", ".join(f"{part_enum_prefix}{name}" for name in part_names) +
        f", {part_enum_prefix}PART_COUNT }};",
        "enum { " + ", ".join(f"{slot_enum_prefix}{name}" for name in slot_names) + " };",
        "",
    ]
    lines.extend(extra_defines)
    lines.append("")
    for mesh_name, parts in meshes.items():
        names = [p.name.upper() for p in parts]
        assert names == part_names, (mesh_name, names)
        assert len(parts) <= 24
        vertices: list[tuple[float, ...]] = []
        faces: list[tuple[int, int, int]] = []
        part_rows = []
        for part in parts:
            first_vertex = len(vertices)
            first_face = len(faces)
            vertices.extend(part.vertices)
            faces.extend((a + first_vertex, b + first_vertex, c + first_vertex) for a, b, c in part.faces)
            part_rows.append(
                f"    {{ {part.parent}, {slot_enum_prefix}{part.slot.upper()}, "
                f"{part.pivot[0]:.4f}f, {part.pivot[1]:.4f}f, {part.pivot[2]:.4f}f, "
                f"{first_vertex}, {len(part.vertices)}, {first_face}, {len(part.faces)} }},")
        assert len(vertices) < 65535
        lines.append(f"/* {mesh_name}: {len(vertices)} vertices, {len(faces)} triangles. */")
        lines.append(f"static const dla_rig_vertex_t {mesh_name}_vertices[{len(vertices)}] = {{")
        for v in vertices:
            lines.append("    { " + ", ".join(f"{value:.4f}f" for value in v) + " },")
        lines.append("};")
        lines.append(f"static const dla_rig_face_t {mesh_name}_faces[{len(faces)}] = {{")
        for row in range(0, len(faces), 6):
            lines.append("    " + " ".join(f"{{{a},{b},{c}}}," for a, b, c in faces[row:row + 6]))
        lines.append("};")
        lines.append(f"static const dla_rig_part_t {mesh_name}_parts[{part_enum_prefix}PART_COUNT] = {{")
        lines.extend(part_rows)
        lines.append("};")
        lines.append("")
    lines.append(f"static const dla_rig_mesh_t {table_name}{table_shape} = {{")
    for row in table_rows:
        entries = []
        for mesh_name in row:
            parts = meshes[mesh_name]
            entries.append(f"{{ {mesh_name}_vertices, {mesh_name}_faces, {mesh_name}_parts, "
                           f"{sum(len(p.vertices) for p in parts)}, {sum(len(p.faces) for p in parts)}, "
                           f"{part_enum_prefix}PART_COUNT }}")
        if len(row) == 1:
            lines.append("    " + entries[0] + ",")
        else:
            lines.append("    { " + ", ".join(entries) + " },")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_obj(path: Path, name: str, world: list[tuple[float, float, float]],
              parts: list[Part], uv_offsets: list[tuple[float, float]],
              skip: list[bool], x_offset: float = 0.0) -> None:
    obj = [f"mtllib {name}.mtl", f"usemtl {name}", f"o {name}"]
    for (x, y, z) in world:
        obj.append(f"v {x + x_offset:.5f} {y:.5f} {z:.5f}")
    offset = 0
    uvs, normals, faces = [], [], []
    for index, part in enumerate(parts):
        du, dv = uv_offsets[index]
        for v in part.vertices:
            uvs.append(f"vt {v[3] + du:.5f} {1.0 - (v[4] + dv):.5f}")
            normals.append(f"vn {v[5]:.4f} {v[6]:.4f} {v[7]:.4f}")
        if not skip[index]:
            for a, b, c in part.faces:
                faces.append("f " + " ".join(f"{i + offset + 1}/{i + offset + 1}/{i + offset + 1}" for i in (a, b, c)))
        offset += len(part.vertices)
    obj.extend(uvs)
    obj.extend(normals)
    obj.extend(faces)
    path.write_text("\n".join(obj) + "\n", encoding="utf-8")
    path.with_suffix(".mtl").write_text(f"newmtl {name}\nKd 1 1 1\nmap_Kd {name}.png\n", encoding="utf-8")
