N = N + 1: PRINT "HELLO"; N
IF N < 3 THEN GOTO 1
GOSUB 6
IF R = 0 THEN R = 1: PRINT "AGAIN": N = 5: GOTO 9
END
PRINT "SUB AT EDITOR LINE 6": RETURN
PRINT "NOT REACHED"
GOTO 99
PRINT "N IS"; N: GOTO 8
